### ISSUE TITLE
[Feature Request] XDG Compliance

### ISSUE THREAD

**Issue by BenEvolent333** [gmgauthier/gostations#1]
I modified the config.go file to add complaince for both XDG_CONFIG_HOME, or (if that variable is not set) "~/.config", both with the file at "/gostations/radiostations.ini". Here is the 

> diff --git a/config.go b/config.go
index d5e7730..8b89e21 100644
--- a/config.go
+++ b/config.go
@@ -22,6 +22,11 @@ func str2int(strnum string) int {
 func Config(option string) (string, error) {
 	configparser.Delimiter = "="
 	configFile := "radiostations.ini"
\+        xdgConfigPath := os.Getenv("XDG_CONFIG_HOME")
\+        if xdgConfigPath == "" {
\+          xdgConfigPath = "~/.config"
\+        }
\+        configFile = xdgConfigPath + "/gostations/" + configFile
> 	runtimeSection := "DEFAULT"
 
> 	config, err := configparser.Read(configFile)
@@ -59,4 +64,4 @@ func options() string {
 func maxitems() int {
 	items, _ := Config("menu_items.max")
 	return str2int(items)
\-}
\ No newline at end of file
\+}

Sorry about the last part, I guess vim added a newline.

**Comment by gmgauthier** [comment]
I love it! Thanks! I'm definitely adding this.
